# Generated by Django 3.1.7 on 2021-04-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_solo_app', '0002_web_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Li_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='li_job',
            old_name='job_index',
            new_name='data_id',
        ),
        migrations.AddField(
            model_name='li_job',
            name='criteria',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='li_job',
            name='data_search_id',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='li_job',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='li_job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Li_Jobs', to='project_solo_app.li_company'),
            preserve_default=False,
        ),
    ]
