# Generated by Django 3.1.7 on 2021-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_solo_app', '0003_auto_20210417_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Scrape_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField()),
                ('count', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
