# Generated by Django 3.1.7 on 2021-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_solo_app', '0004_web_scrape_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('current', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Web_Scrape',
        ),
    ]
