# Generated by Django 3.1.7 on 2021-04-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_solo_app', '0005_auto_20210418_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='source',
            field=models.CharField(default='Google', max_length=255),
            preserve_default=False,
        ),
    ]
