# Generated by Django 3.1.7 on 2021-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_solo_app', '0006_definition_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='li_job',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
